
FROM golang:alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bully-election

FROM scratch

COPY --from=builder /bully-election /bully-election

ENTRYPOINT ["/bully-election"]