services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
      timeout: 3s

  auth-service:
    build: ./auth-service
    expose:
      - "3001"
    environment:
      - REDIS_HOST=redis
    networks:
      - backend
    depends_on:
      - redis

  profile-service:
    build: ./profile-service
    expose:
      - "3002"
    environment:
      - REDIS_HOST=redis
    networks:
      - backend
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      auth-service:
        condition: service_started
      profile-service:
        condition: service_started
      redis:
        condition: service_healthy

networks:
  backend:
    driver: bridge
